### ISSUE TITLE
As Mary I want to see a quick overview of recent recalls so that I get a sense of recall activity and need not sift through long lists of data upfront

### ISSUE THREAD

**Issue by michaelgaigg** [esridc/openfda#32]
User sees a summary of recalls for the past 7 days.
User can click on one of three button
- # Dangerous
- # Slight threat
- # unlikely health risk

![uploads/d6acc33b-1482-4328-9862-d32b8d569ac2/Call to action.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd6acc33b-1482-4328-9862-d32b8d569ac2%2FCall+to+action.png)

**Comment by benheb** [comment]
Handled a bit differently because no popup was built, but Mary is able to sort by latest most recent recalls, and see a summarized count for each category in the list tab. Closing as resolved.  

![gsa_18f_prototype](https://cloud.githubusercontent.com/assets/910495/8441594/87ffa87a-1f36-11e5-
9eea-96e55273efc8.jpg)
