### ISSUE TITLE
Usability Test 2:  Persona test with Mary - Manager of Food Services @ Arizona Hospital

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#39]
Usability test: Have employee play the role of Mary - Manger of Food Services for a chain of Hospitals in Arizona.

Reassure them that there is no right/wrong answer - looking for their feedback and comments.

Show them a paper copy of the current wire frame and watch their interaction and report. Show one page at a time and ask them how they would navigate, and what their expectations would be for the results.

Can they answer the question:

"What recalls have been made recently by FDA for Arizona"

**Comment by jlbraden** [comment]
Observations from usability test:
https://github.com/esridc/openfda/wiki/WireframesIteration1

General Comments
- City layer is underneath State layer, so City names are not visible
- Subtitle "Find harmful or deceptive products" does not read well, change to "Find recalled products in your area" or something similar
- Orange color of State layer may be confused with orange color of "Slight Threat" category (see suggested change of color under Call to Action)

Empty State
- Workflow is clear - you can type in the state, city, or zip to search OR click on state in the map
- How does this data relate/compare to FDA's current recalls website?

Call to Action
- Workflow - thought you would select one of the boxes to get more details on the result; should be one-click
- Are these totals all active or just new within the timeframe? I actively follow recalls, so I am only interested in what is new.
- What do the categories mean? Do they correspond to FDA's Class 1, Class 2, and Class 3? If so, then the labels should indicate this.
- What does the Subscribe to Feed button mean?
- Would like it to be clear that the products are being SOLD in Arizona, not that they ORIGINATE in Arizona; change title to "Products available in Arizona subject to recall" or similar

Recall List
Does this list give you the information you need?
- Map isn't providing any useful information
- If I click on Show Details, will it show stores where item was purchased?
- Can I determine if the locations are retail or wholesale? As a hospital administrator, I am more interested in wholesale locations.

Recall Details
- What does initiate date mean? There appears to be a large gap between Initiate Date and Report Date
- Can we see where the food is? Where it was purchased from? As a consumer, that's really what I want to know.

**Comment by michaelgaigg** [comment]
Recommendations from UX team:
- Consider changing the tagline to "Find recalled products in your state"
- Use neutral cartographic symbology (e.g. blue) so that a selected state isn't mistaken as dangerous (if it was orange)
- Highlight recalls that are new (e.g. within the last week) so that a user that is following the listing closely can easily identify the new ones
- Subscribe to feed function (or label) wasn't clear. Questioning whether users would be familiar with this concept
- Question to dev team: is there a way to state whether a recall affects retail or wholesale? This would be important to know for Mary
- Eliminate confusing / conflicting data; possibly change labels or representation or question whether to show in the first place?
