### ISSUE TITLE
Usability Test 3:  Persona test with Dr Bob - Researcher at University

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#40]
Usability test: Have employee play the role of Dr Bob - Researcher at a University.  

Reassure them that there is no right/wrong answer - looking for their feedback and comments.

Show them a paper copy of the current wire frame and watch their interaction and report. Show one page at a time and ask them how they would navigate, and what their expectations would be for the results.

Can they answer the question:

"What recalls have been made recently by FDA for Arizona"

**Comment by jlbraden** [comment]
Observations from usability test:
https://github.com/esridc/openfda/wiki/WireframesIteration1 

General Comments
- City layer is underneath State layer, so City names are not visible
- Subtitle "Find harmful or deceptive products" does not read well, change to "Find recalled products in your area" or something similar
- Orange color of State layer may be confused with orange color of "Slight Threat" category (see suggested change of color under Call to Action)

Empty State
- Workflow is clear - you can type in the state, city, or zip to search OR click on state in the map
- Not clear how you would view information on a national scale

Call to Action
- Workflow - thought you would just click on Show Detail About these Recalls, but ideally would want to be able to just click on the summary box you are interested in to take you to details about that category (one-click)
- Color of the summary boxes/buttons should be Red, Orange, Yellow to indicate severity; Blue does not make sense
- Initial view only shows Last 7 days - would be helpful if we could go back further to address items that sit longer on the shelf; 30, 60, and 90 day options?

Recall List
Does this list give you the information you need?
- Map isn't providing any useful information; would be helpful to see states shaded by total number of active recalls to provide some more context
- Confusion over orange line at the top of the panel (presumably this is indicating the active tab?)

Recall Details
- What happens when Show on Map is clicked? Would like to see states shaded base on amount/number of locations. Ideally, would like the ability to drill down to actual locations of stores where recalled foods were purchased (e.g., locations of Safeways, Costcos, etc.)

**Comment by michaelgaigg** [comment]
Recommendations from UX team:
- Filter for recall data based on date appears to be of importance to the user
- General comment about the map after selecting a state: Is there anything useful that can be displayed (when in list view; when in details view)?
