### ISSUE TITLE
Develop Personas

### ISSUE THREAD

**Issue by ajturner** [esridc/openfda#5]

**Comment by gclancy** [comment]
Persona #1:  Manager of Food Services for a chain of hospitals in Arizona.  Concerned about food recalls that may affect their facilities.  Not tech savvy.  Wants to be able to display on any device.

**Comment by gclancy** [comment]
Persona #2:  Bob, Researcher at a University on Food Safety.  Very technical and likes details.  wants a lot of data to understand the big picture but also to drill down to local details as well.  Male - mid 40;s.  Wants to be able to look at trends of food recalls over time - so that he can validate patterns and determine if there are unusual trends.  Very visual.  Prefers to use a tablet or large monitor to view information - does not use his mobile phone to view data (only emails).

**Comment by gclancy** [comment]
Persona #3:  Ann, Stay at home mom - early 30's.  Two kids with extensive allergies and concerned about food safety.  Wants to be able to get an alert on a timely basis when a food recall happens that affects her address.  She does everything on a mobile phone - hectic schedule and does not have time to go look at web sites.

**Comment by michaelgaigg** [comment]
added personas to the wiki: https://github.com/esridc/openfda/wiki
