### ISSUE TITLE
Issue with showing recalls and affected states..  recall for this product is nationwide but line only goes to one state..Indiana

### ISSUE THREAD

**Issue by gclancy** [esridc/openfda#53]
![image](https://cloud.githubusercontent.com/assets/13022624/8386538/459166f0-1c1f-11e5-952c-92fc491d8fa9.png)

**Comment by benheb** [comment]
@gclancy Good catch. Goes back to challenges with the API. The string I'm parsing to figure out what states are impacted can have pretty much anything. Instead of listing the states, it just says "Nationwide". I've resolved this issue, and opened a PR (https://github.com/esridc/openfda/pull/55). Now this one looks like: 

![open_fda](https://cloud.githubusercontent.com/assets/910495/8386928/a6a01fd0-1c11-11e5-807c-645a858390da.jpg)
